### ISSUE TITLE
SPP `get_status` Failing

### ISSUE THREAD

**Issue by kmax12** [kmax12/gridstatus#109]
`SPP.get_status` scrapes the SPP [current grid conditions](https://www.spp.org/markets-operations/current-grid-conditions/) page

When originally implemented that page looked like [this](https://web.archive.org/web/20221026035146/https://www.spp.org/markets-operations/current-grid-conditions/)

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/371792/209847270-6aa1b2ac-b264-4013-8a05-96d2875be566.png">

However, SPP grid conditions page currently looks like this, leading to parsing issue. Note the change in where the updated at time and status are displayed

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/371792/209847330-672771eb-91f1-4af9-a22e-bbf0686207aa.png">

## Expected Behavior

It's not clear to me if this is just a temporary format change or not. Let's wait at least few days to see what happens with the page structure before revisiting the implementation.

**Comment by jcsalterego** [comment]
:eyes:

**Comment by kmax12** [comment]
appears as if the page hasn't change. i'm guessing parsing this page will be a bit of whack a mole. probably worth building a add a scraper for the current format. then have the method try scrapers until one works.
