### ISSUE TITLE
Refactor tests

### ISSUE THREAD

**Issue by kmax12** [kmax12/gridstatus#118]
Let's refactor `test_isos.py`. Below are some initial thoughts

## Goal

1. Make it easy to run only tests for a specific ISO
3. Make it easy to identify which ISOs have failing tests
4. Keep shared testing code in a central location
5. Still allow iso specific tests to be written

## Proposed approach

Outlined in this branch: https://github.com/kmax12/gridstatus/blob/5ad2795d397c400d20d0a4b71023eab01ef638ff/gridstatus/tests/test_subclass.py

## Open questions

* How do we specify tests that are shared by some, but not all ISO. e.g `test_get_latest_status`

**Comment by jcsalterego** [comment]
👀

**Comment by WillKoehrsen** [comment]
I think this has been completed. Running tests for a specific iso can be done with `pytest gridstatus/tests/test_{iso}.py`. Shared testing functionality is in `base_test_iso.py`.
