### ISSUE TITLE
Standard Logging Function

### ISSUE THREAD

**Issue by kmax12** [kmax12/gridstatus#120]
This issue tracks making a standardized logging function.

The codebase currently has a lot of blocks the following structure

```python
if verbose:
    print(msg)
```

As a first pass, I am thinking something simple like

```python
def log(msg: str, verbose: bool = False) -> None:
    if verbose:
        print(msg)
```

```python
gridstatus.log("This is a message", verbose=True)  # prints "This is a message"
gridstatus.log("This is a message", verbose=False) # does nothing
```

## Questions
- Print to stderr or stdout? Should this be a parameter
- Supporting logging to file
- Use python's builtin `logging` module

**Comment by bendnorman** [comment]
Have you considered using python's buildin`logging` module? You could log important information at the `INFO` level and more verbose information at the `DEBUG` level.

**Comment by kmax12** [comment]
yep. i think it probably makes sense to use the builtin logging module. not adamant it was to be done right away, but the goal of centralizing logging is to make it easier to swap in whatever approach we want without have to change it in multiple places.

**Comment by gsheni** [comment]
What about something as simple as this? 

```python
import logging

def log(msg, verbose=False):
    log = logging.getLogger('gridstatus')
    if verbose:
        log.debug(msg)
    else:
        log.info(msg)
```

```python
# anywhere verbose is used
# example - nyiso.py 
log(msg=f"Requesting {url}", verbose=verbose)
```

**Comment by kmax12** [comment]
how does user configuration work? by default , not sure I want the timestamp and debug level printed every time someone uses the log function. That being said, I can see people would want it
