### ISSUE TITLE
add load areas to PJM get_load

### ISSUE THREAD

**Issue by mconlow** [kmax12/gridstatus#158]
Hi all, Excited to have found this project! I hope I can contribute as I learn the code better, but for now, a quick upvote on adding the "load areas" underneath PJM, as noted in the code here:

https://github.com/kmax12/gridstatus/blob/main/gridstatus/pjm.py#L111

Thanks again!

**Comment by kmax12** [comment]
this is been on my todo list, so thanks for the nudge. 

started an implementation here: #160. will likely need to polish off tomorrow before merging.

keep the suggestions coming and I hope you can contribute sometime as well!
