### ISSUE TITLE
miso get_lmp time conversion issue

### ISSUE THREAD

**Issue by mconlow** [kmax12/gridstatus#163]
The miso get_lmp method is having trouble with the time column. The miso API returns:

`"RefId":"18-Feb-2023 - Interval 18:50 EST"`

The [code](https://github.com/kmax12/gridstatus/blob/main/gridstatus/miso.py#L149) does: 

`        time_str = time[:11] + " " + time[-9:]
        time = pd.to_datetime(time_str).tz_localize("EST")`

and it returns the following error:

`TypeError: Cannot localize tz-aware Timestamp, use tz_convert for conversions`

I think probably the tz_localize is unnecessary?

**Comment by kmax12** [comment]
Can you share a reproducible example?

I get the following running locally. I get an warning, but not the type error

```
>>> import gridstatus
>>> iso = gridstatus.MISO()
>>> iso.get_lmp("latest", market="DAY_AHEAD_HOURLY")
/Users/kanter/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/dateutil/parser/_parser.py:1207: UnknownTimezoneWarning: tzname EST identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  warnings.warn("tzname {tzname} identified but not understood.  "
                         Time            Market        Location Location Type    LMP  Energy  Congestion  Loss
0   2023-02-18 20:00:00-05:00  DAY_AHEAD_HOURLY    CONS.MCV.MCV  Pricing Node  25.75   26.24        0.42 -0.91
1   2023-02-18 20:00:00-05:00  DAY_AHEAD_HOURLY  CONS.PALISA2A1  Pricing Node  26.30   26.24        0.00  0.06
2   2023-02-18 20:00:00-05:00  DAY_AHEAD_HOURLY  CONS.WPSC_2.AZ  Pricing Node  27.22   26.24        0.24  0.74
3   2023-02-18 20:00:00-05:00  DAY_AHEAD_HOURLY            CPLE  Pricing Node  27.71   26.24        1.04  0.43
4   2023-02-18 20:00:00-05:00  DAY_AHEAD_HOURLY            CPLW  Pricing Node  27.89   26.24        1.17  0.48
..                        ...               ...             ...           ...    ...     ...         ...   ...
340 2023-02-18 20:00:00-05:00  DAY_AHEAD_HOURLY    CIN.GIBSON.3  Pricing Node  28.51   26.24        1.68  0.59
341 2023-02-18 20:00:00-05:00  DAY_AHEAD_HOURLY    CIN.GIBSON.4  Pricing Node  28.51   26.24        1.68  0.59
342 2023-02-18 20:00:00-05:00  DAY_AHEAD_HOURLY    CIN.GIBSON.5  Pricing Node  28.51   26.24        1.68  0.59
343 2023-02-18 20:00:00-05:00  DAY_AHEAD_HOURLY         CIN.PSI  Pricing Node  28.89   26.24        1.61  1.04
344 2023-02-18 20:00:00-05:00  DAY_AHEAD_HOURLY      CLEC.ACA11  Pricing Node  26.50   26.24        0.01  0.25

[345 rows x 8 columns]
```

**Comment by mconlow** [comment]
Huh, weird. Maybe a different python version?

`df = miso.get_lmp(date="latest",verbose=True, market="REAL_TIME_5_MIN", locations="ALL")
df`

`
~/dev/pypsa/venv/lib/python3.7/site-packages/gridstatus/miso.py in get_lmp(self, date, market, locations, verbose)
    148         time = r["LMPData"]["RefId"]
    149         time_str = time[:11] + " " + time[-9:]
--> 150         time = pd.to_datetime(time_str).tz_localize("EST")
    151 
    152         if market == Markets.REAL_TIME_5_MIN:

~/dev/pypsa/venv/lib/python3.7/site-packages/pandas/_libs/tslibs/timestamps.pyx in pandas._libs.tslibs.timestamps.Timestamp.tz_localize()

TypeError: Cannot localize tz-aware Timestamp, use tz_convert for conversions
`

**Comment by kmax12** [comment]
Looking at it more, fairly certain the warning and error are the same issue. Must just be different versions of something cause the difference. 

Refactor the code to make the warning go away in #164. If you have a chance, can you try to install main and let me know if the issue goes away for you?

**Comment by mconlow** [comment]
Ok, I started over with a clean environment and installed main and it's working now. 

I went up to python 3.9.1, thought I'm not sure python version was the issue before. I also had wound up with pyarrow along the way previously but I removed that in this environment.

Thanks!
