### ISSUE TITLE
Add Code Coverage

### ISSUE THREAD

**Issue by kmax12** [kmax12/gridstatus#165]
Would be nice to generate a codecoverage number like libraries such as https://github.com/alteryx/featuretools

<img width="761" alt="image" src="https://user-images.githubusercontent.com/371792/219980295-f2549c41-1db2-4465-925d-dee3edb903ac.png">

Should to add to both readme and github actions that run on every PR

**Comment by gsheni** [comment]
take

**Comment by kmax12** [comment]
awesome! is this possible without creating an account somewhere that's not github?

**Comment by gsheni** [comment]
I think if you want to use Codecov, you'll have to setup the repo and put the upload token into the GitHub Actions secrets.
- https://docs.codecov.com/docs/quick-start

**Comment by gsheni** [comment]
Alternatively, I can try to setup [coveragepy](https://github.com/nedbat/coveragepy)
The benefit of **Codecov** is that it will host the reports, where as with **coveragepy** the coverage reports (HTMLs) would have to be hosted somewhere.
