### ISSUE TITLE
Ercot Real time SPP missing final hour data because of how HE is handled

### ISSUE THREAD

**Issue by iamanonym0us** [kmax12/gridstatus#223]
[RT_05212023.csv](https://github.com/kmax12/gridstatus/files/11535928/RT_05212023.csv)

Please look at the data for yesterday's ERCOT RT_SPP. Time starts with 1:00 and ends at 23:00. Therefore its missing final hour data. I checked the code and its fetching all the necessary files. But its not getting added because of how the time data is handled. 24:15 is invalid time and therefore not shown in the data.  The data in 23:XX is actually data for 22:XX. 

To replicate run with yesterdays date :
rtdf = iso.get_spp(date="May 21 2023", market="REAL_TIME_15_MIN", location_type="node")

**Comment by kmax12** [comment]
When I run the code that is currently on main, I am not seeing what you describe.

The earliest data point is at the beginning of the day. However, I am seeing that the last 15 interval of the day is missing

```python
>>> import gridstatus 
>>> iso = gridstatus.Ercot()
>>> df = iso.get_spp(date="May 21, 2023", market="REAL_TIME_15_MIN")
>>> df
                           Time            Interval Start              Interval End      Location  Location Type            Market    SPP
0     2023-05-21 00:00:00-05:00 2023-05-21 00:00:00-05:00 2023-05-21 00:15:00-05:00   YNG_WND_ALL  Resource Node  REAL_TIME_15_MIN  36.08
1     2023-05-21 00:00:00-05:00 2023-05-21 00:00:00-05:00 2023-05-21 00:15:00-05:00   FOXTROT_ALL  Resource Node  REAL_TIME_15_MIN  36.08
2     2023-05-21 00:00:00-05:00 2023-05-21 00:00:00-05:00 2023-05-21 00:15:00-05:00  FORMOSA_PUN2  Resource Node  REAL_TIME_15_MIN  36.08
3     2023-05-21 00:00:00-05:00 2023-05-21 00:00:00-05:00 2023-05-21 00:15:00-05:00  FORMOSA_PUN1  Resource Node  REAL_TIME_15_MIN  36.08
4     2023-05-21 00:00:00-05:00 2023-05-21 00:00:00-05:00 2023-05-21 00:15:00-05:00   FORMOSA_CC2  Resource Node  REAL_TIME_15_MIN  36.08
...                         ...                       ...                       ...           ...            ...               ...    ...
79510 2023-05-21 23:30:00-05:00 2023-05-21 23:30:00-05:00 2023-05-21 23:45:00-05:00  PANDA_T2_CT1  Resource Node  REAL_TIME_15_MIN  19.63
79511 2023-05-21 23:30:00-05:00 2023-05-21 23:30:00-05:00 2023-05-21 23:45:00-05:00  PANDA_T2_CC1  Resource Node  REAL_TIME_15_MIN  19.63
79512 2023-05-21 23:30:00-05:00 2023-05-21 23:30:00-05:00 2023-05-21 23:45:00-05:00  PANDA_T1_ST1  Resource Node  REAL_TIME_15_MIN  19.63
79513 2023-05-21 23:30:00-05:00 2023-05-21 23:30:00-05:00 2023-05-21 23:45:00-05:00  NUE_NUECESG9  Resource Node  REAL_TIME_15_MIN  19.63
79514 2023-05-21 23:30:00-05:00 2023-05-21 23:30:00-05:00 2023-05-21 23:45:00-05:00          AEEC  Resource Node  REAL_TIME_15_MIN  19.63
```

 It's possible that this has been fixed since the last release. I am going to investigate what going on with the interval and once that is resolved, I will make a new release.

**Comment by iamanonym0us** [comment]
Looks like it might have been fixed in your pre release. I am seeing that the code is different. And about the last interval, i know what is going on. You're using "Published date" to match and fetch the files. The last interval is actually published the next day at 12:02. But some how its not getting picked on both days. Maybe you should just fetch the first file from next day to get that last interval. Thank you.

**Comment by kmax12** [comment]
yep, I see the problem. just put up #224 to resolve. should have new release out by end of day

**Comment by iamanonym0us** [comment]
Thanks

**Comment by kmax12** [comment]
should be fixed in `v0.21.0` which was just released. let me know if you still see issues.

**Comment by iamanonym0us** [comment]
For some reason am getting empty dataframe after updating

**Comment by iamanonym0us** [comment]
Investigated further. If i specify any location type here like this , iso.get_spp(date="May 21, 2023", market="REAL_TIME_15_MIN",location_type="hub") i get empty data frame. If I don't specify anything I am getting data.

**Comment by iamanonym0us** [comment]
Figured it out. Looks like you have changed Iso.location_types. That was causing the issues. Please update the documentation. Thank you

**Comment by kmax12** [comment]
sorry about that. should be fixed everywhere now, but let me know if you are still seeing it incorrectly anywhere
