### ISSUE TITLE
Support Pandas 2.0.1

### ISSUE THREAD

**Issue by kmax12** [kmax12/gridstatus#228]
There is at least one bug introduce in pandas 2.0.1

https://github.com/kmax12/gridstatus/issues/227#issuecomment-1560441715

**Comment by DavidRothblum** [comment]
Hi @kmax12 -- came across this repo recently. Any plans to tackle Pandas 2 support in the near future?

**Comment by kmax12** [comment]
it's not currently scheduled to be worked on, but definitely still on our radar. we know there is at least one issue, but we haven't sized it up yet

first step here is to do the upgrade and then see how the test cases do

if there isn't much to fix, i suspect we can add support somewhat quickly. And we'd then drop Pandas <2 support.

**Comment by WillKoehrsen** [comment]
I wonder if we should wait until Pandas 3 is out and skip over 2? The stable release is [scheduled for April 1, 2024](https://github.com/pandas-dev/pandas/milestone/102).

**Comment by WillKoehrsen** [comment]
Completed in #345 and released in #349 thanks to @DavidRothblum!
