### ISSUE TITLE
ERCOT upload "retry" leading to document filter issue

### ISSUE THREAD

**Issue by marcus-maro** [kmax12/gridstatus#232]
On 2023/06/08, it appears ERCOT unsuccessfully uploaded a file under the "Settlement Point Prices at Resource Nodes, Hubs and Load Zones" data product (https://www.ercot.com/mp/data-products/data-product-details?id=NP6-905-CD), resulting in a file named "SPPHLZNP6905_retry_20230608_1545_csv" being uploaded instead.

Due to the added "_retry" in the document name, this file was not included in the document filtering and therefore missing from the returned data. Below is the section of code that does this filtering.

https://github.com/kmax12/gridstatus/blob/b29663791ed30635bb7e09be403b11586bc6ee01/gridstatus/ercot.py#L824-L836

To replicate (using v0.21.0):
```
import gridstatus
import pandas as pd

ercot = gridstatus.Ercot()

start = pd.Timestamp("2023-06-08", tz="US/Central")
end = pd.Timestamp("2023-06-09", tz="US/Central")

df_rt = ercot.get_spp(start, end, market="REAL_TIME_15_MIN")
```

**Comment by kmax12** [comment]
thank you for posting. I will look into fixing this ASAP

**Comment by kmax12** [comment]
I believe i fixed the logic to handle files named with retry. I added a test case, but hard to test on live data since these files dont always exist. if you or anyone else sees issues, we can reopen this issue. thanks for reporting!
