### ISSUE TITLE
Add LMP Data for ERCOT

### ISSUE THREAD

**Issue by kmax12** [kmax12/gridstatus#24]
Some potential sources: 

https://www.ercot.com/mktinfo
https://www.ercot.com/api/1/services/read/dashboards/systemWidePrices.json
https://www.ercot.com/mp/data-products/markets/real-time-market?id=NP6-788-CD

**Comment by jcsalterego** [comment]
Ah perhaps average per Hub? 
<img width="468" alt="image" src="https://user-images.githubusercontent.com/30475/207905088-48146302-a251-445b-aad9-20102c479390.png">

**Comment by kmax12** [comment]
Every ISO has slightly different schemes for this for naming things. I am not 100% but here is my interpretation of how things work for Ercot.

Location Types: 

* Resource Nodes,
* Hubs
* Load Zones. 

The Hubs and Load Zone are each collections of resource nodes. I think a "Settlement Point" is just a generic name for an individual Resource Nodes, Hubs and Load Zones. 

In terms of data sources, I think DAM prices for all three can be found here: https://www.ercot.com/mp/data-products/data-product-details?id=NP4-190-CD

And, I think Real-time is this one: https://www.ercot.com/mp/data-products/data-product-details?id=NP6-905-CD

I need to look more closely, but these are the datasets linked at the bottom of this dashboard for system-wide prices: https://www.ercot.com/gridmktinfo/dashboards/systemwideprices. I don't have good internet at the moment, but if we can confirm those reports match the data returned from the endpoint being used on the dashboard (https://www.ercot.com/api/1/services/read/dashboards/systemWidePrices.json), I think they are what needs to be added

**Comment by jcsalterego** [comment]
> Location Types:
> 
> * Resource Nodes
> * Hubs
> * Load Zones

For consistency within the API across ISOs, what are you thinking for valid `location_type` values in ERCOT? "hub", "zone" and ... "node"?

**Comment by kmax12** [comment]
I'm not sure if Load zone vs Zone is significant. For now, I think let's just do Load Zone. Hub and node seem fine.

Will dig into meaning of zone in places like NYISO more next week when I'm back at my computer

**Comment by WillKoehrsen** [comment]
We now have ERCOT LMP by bus and settlement points (#282) and ERCOT LMP DAM by bus (#348). Closing issue as completed.
