### ISSUE TITLE
Can you tell me from which website did you collect the 'isone_load' data?

### ISSUE THREAD

**Issue by laplace666666** [kmax12/gridstatus#249]
Can you tell me from which website did you collect the 'isone_load' data?
![image](https://github.com/kmax12/gridstatus/assets/119828956/6c8618b7-312e-4f14-8e87-ed5c27666841)
The data I obtained from 'gridstatus' is reported every five minutes, but I cannot find such data from https://www.iso-ne.com/isoexpress/web/reports/load-and-demand/ I only found one hourly load data report. Looking forward to your reply, thank you!

**Comment by kmax12** [comment]
You can see the code here: https://github.com/kmax12/gridstatus/blob/main/gridstatus/isone.py#L157
