### ISSUE TITLE
ERCOT LZEW vs LZ data

### ISSUE THREAD

**Issue by jcfd3** [kmax12/gridstatus#271]
`gridstatus` version `0.22.0`. 

```
        # todo figure out why
        # when you get rid of SettlementPointType some
        # rows are duplicated
        # For example, SettlementPointType LZ and LZEW
        df = df.drop_duplicates(
            subset=[
                "Time",
                "Interval Start",
                "Interval End",
                "Location",
            ],
        )
```

## Issue
Why are `LZEW` and `LZ` considered the same data? Checking directly with ERCOT, they are different data points, of which LZEW seems to be "load zone energy weighted" unless I am mistaken.

Thank you!

**Comment by kmax12** [comment]
you are right. this has been fixed and will go out in the next release. i'll try to do that later today

https://github.com/kmax12/gridstatus/pull/256
