### ISSUE TITLE
ERCOT LMP

### ISSUE THREAD

**Issue by kmax12** [kmax12/gridstatus#280]
Add this dataset: LMPs by Resource Nodes, Load Zones and Trading Hubs

https://www.ercot.com/mp/data-products/data-product-details?id=NP6-788-CD

Similar to sced_system_lambda

**Comment by Michael-fore** [comment]
# LMPs by Resource Nodes, Load Zones and Trading Hubs
# https://www.ercot.com/mp/data-products/data-product-details?id=NP6-788-CD
LMP_BY_RESOURSE_NODES = 12300

**Comment by kmax12** [comment]
implemented in #282
