### ISSUE TITLE
Forecast Time of CAISO

### ISSUE THREAD

**Issue by leoniewgnr** [kmax12/gridstatus#291]
What is the forecast time of the load forecast of CAISO? Because this depends on the column 'LABEL' taken from the oasis data:
`Demand Forecast 2-Day Ahead` or `Demand Forecast Day Ahead`?
https://github.com/kmax12/gridstatus/blob/797f770165aebd20eb44a92788418a915f6d3727/gridstatus/caiso.py#L201C11-L201C11

**Comment by DA-Mike** [comment]
@kmax12 Mind if I take this one to add all of the markets?

**Comment by kmax12** [comment]
Go for it!

**Comment by DA-Mike** [comment]
Thanks! Can you make me a contributor so I can branch the issue?

**Comment by WillKoehrsen** [comment]
CAISO DAM load forecast is published at 9:10 AM PT according to OASIS. We've implemented this publish time in the `get_load_forecast`.

<img width="978" alt="Screenshot 2024-05-06 at 15 40 01" src="https://github.com/kmax12/gridstatus/assets/17484616/fc43af12-da9a-489e-860e-8ad956db1efd">


https://github.com/kmax12/gridstatus/blob/c4bb61de66db55b51b8018ba3bd478898c1e0cf5/gridstatus/caiso.py#L209-L215
