### ISSUE TITLE
Allow access to raw ISO interconnection queue data?

### ISSUE THREAD

**Issue by jdangerx** [kmax12/gridstatus#305]
Hi! I work with @TrentonBush and @bendnorman at [Catalyst Cooperative](https://catalyst.coop/).

## Overview

As mentioned in #76 and #290, there are still some interesting questions about the different ways different ISOs report this data. At Catalyst, we'd like to access the raw data directly, to help understand and answer some of those questions.

## Rough Plan

I think we could do this by adding an `ISOBase.get_raw_interconnection_queue() -> BinaryIO` method to `ISOBase`, along with its subclasses. We'd then consume the output of this in the various `get_interconnection_queue()` methods.

I know, adding to the public API is risky, because that makes promises to all future users. But, if we want to allow people to access the raw data directly, then that behavior must be exposed somehow...

We're already splitting out the raw data extraction in some of the ISO classes, sort of.

For example, in `ISONE.get_interconnection_queue()` we already call `ISONE._extract_interconnection_queue()`, which *mostly* handles all the junk required to get a relevant blob of HTML into memory. It also handles transforming that into a Pandas dataframe at all, before passing control back to the caller which does further transformations on the data.

And in `ERCOT.get_interconnection_queue()` we call `._get_document()`, which handles much of the complicated aspects of the extraction process. We handle the rest of the process in the body of `get_interconnection_queue` itself.

For most of the other ISOs, this `get_raw_interconnection_queue()` would be a very simple method that just runs a GET request.

### Side benefit

This sets us up to split out the logic a little bit more in the future, so that the `get_interconnection_queue()` logic looks something like:

```python
def get_interconnection_queue(self):
    raw_data = self.get_raw_interconnection_queue()
    input_dataframe = pd.read_excel(raw_data, ...)
    cleaned_dataframe = self.transform_interconnection_queue(input_dataframe)
    return cleaned_dataframe
```

Which would allow us to write tests on each ISO's `.transform_interconnection_queue()` methods without having to hit various external APIs - if we so choose.

## Questions

I think the big question is, do you want to allow people to use GridStatus to access the raw interconnection queue data?

If you think that's a worthwhile goal, what do you think of the plan above? What will go wrong / be hard to maintain? Are you OK with making this a public method?

I'm happy to put in a PR if that seems like the right next step.

**Comment by kmax12** [comment]
i think access to raw interconnection queue data is great idea. I originally went into things wanting to standardize it, but eventually realized how difficult that is. 

i would support this proposed. 

thanks!

**Comment by kmax12** [comment]
the only suggestion I have is I think the pseduo code could just be 

```python
def get_interconnection_queue(self):
    raw_data = self.get_raw_interconnection_queue()
    cleaned_dataframe = self._transform_interconnection_queue(raw_data)
    return cleaned_dataframe
```

**Comment by jdangerx** [comment]
Hi @kmax12, thanks for the quick response! I can start working on this now.

In terms of the pseudocode for the future of `get_interconnection_queue` - I think your version is shorter! But it does make it harder to unit test the transform logic, if that's something we'd like to do. In either case, I think that refactor is out of scope for this issue 😉

**Comment by kmax12** [comment]
ahh, i missed that you wanted to `get_raw_interconnection_queue()` to return BinaryIO. i think it would make sense for that to return a minimal processed version of the the interconnection queue into a pandas dataframe. that would make that function call more useful to people that to use it directly

within `get_raw_interconnection_queue()` we could still implement separate functions to make it easier to unit test

**Comment by TrentonBush** [comment]
>  i think it would make sense for that to return a minimal processed version of the the interconnection queue into a pandas dataframe. that would make that function call more useful to people that to use it directly

I can see why that may be useful, but it is not quite compatible with our motivation behind the refactor. Our motivation for the BinaryIO output is to enable archiving of raw data so that future code changes can be applied to the full set of historical data.

For example, some raw ISO queues are Excel files with multiple sheets, only one of which is currently processed by GridStatus. If we only archive a minimally transformed dataframe, those other sheets are lost even if future transformation code is capable of processing them. This is not just hypothetical for us: we likely want to expand the scope of some transformation functions to include other sheets containing withdrawn or completed projects.

Sorry to parachute in with these issues and PRs before getting aligned on the end product -- I didn't quite appreciate the scope until we had done some of the work. Are you available to discuss the compatibility of our respective visions for ISO queue access? Happy to discuss on GH or video call.
