### ISSUE TITLE
NYISO interconnection queue columns have changed

### ISSUE THREAD

**Issue by TrentonBush** [kmax12/gridstatus#323]
NYISO interconnection queues are distributed as 3 sheets in an excel file, one sheet for each of active, withdrawn, and completed projects. Each sheet has slightly different columns, and it appears they may have changed since the `NYISO.get_interconnection_queue()` method was written.
For example, active projects use the label "Points of Interconnection" whereas the other two sheets use "Interconnection Point". This is not currently accounted for in the code, resulting in active projects losing all information about their interconnection points. There may be other differences as well.

**Comment by APIKreative** [comment]
I too am running into this issue.

**Comment by WillKoehrsen** [comment]
@TrentonBush @APIKreative Are there other differences you have noticed? I've opened #329 but it only addresses the "Points of Interconnection" difference.

**Comment by WillKoehrsen** [comment]
I'm going to close this since #329 is merged, but feel free to comment if you find other issues.
