### ISSUE TITLE
Minor issue- broken link in README

### ISSUE THREAD

**Issue by syphax** [kmax12/gridstatus#326]
In the README, the [example notebooks link](https://docs.gridstatus.io/en/latest/Examples/index.html) leads to a 404.

**Comment by WillKoehrsen** [comment]
Thanks for noticing the issue! I think what we need to do is create an `index.md` at `docs/Examples` that contains links to all the ISO example pages (caiso/index.md, ercot/index.md,  nyiso/index.md, etc.) in a `{toctree}`. 

@syphax Did you want to try adding that as a PR?

**Comment by WillKoehrsen** [comment]
Fixed in #327
