### ISSUE TITLE
Use poetry for dependency management

### ISSUE THREAD

**Issue by WillKoehrsen** [kmax12/gridstatus#330]
Is there a specific reason this repo doesn't use poetry (or a comparable tool) for dependency management? `poetry` makes setting up your dev environment much simpler.

**Comment by kmax12** [comment]
The reason is I was copying GitHub actions from another open source repo and that didn't use poetry. Would love to convert to poetry here

**Comment by WillKoehrsen** [comment]
Completed in #338
