### ISSUE TITLE
EIA_API_KEY for local testing

### ISSUE THREAD

**Issue by tylercecil** [kmax12/gridstatus#332]
I recently forked, and (as per the contrib document) ran the tests. They failed because `EIA_API_KEY` was not set. 

```sh
> pytest gridstatus/tests/test_eia.py
=========================== short test summary info ===========================
FAILED gridstatus/tests/test_eia.py::test_list_routes - KeyError: 'response'
FAILED gridstatus/tests/test_eia.py::test_rto_interchange - KeyError: 'respo...
FAILED gridstatus/tests/test_eia.py::test_rto_region_data - KeyError: 'respo...
FAILED gridstatus/tests/test_eia.py::test_fuel_type - KeyError: 'response'
======================== 4 failed, 3 passed in 33.67s =========================

> export EIA_API_KEY="9e1a7ae3ce839e9ad174eb4028b7a7b2"
> pytest gridstatus/tests/test_eia.py
======================= 7 passed, 2 warnings in 45.19s ========================

```

This was addressed in #310 for the github workflow. What is intended for local test runs? Are developers expected to have their own keys, or should this key be folded into the testing code (or elsewhere)? 

(Sorry if this is a silly question!)

**Comment by WillKoehrsen** [comment]
Not a silly question! You can either use your own key from the EIA (free [here](https://www.eia.gov/opendata/register.php) but you have to register) or the one from `tests.yaml`.

**Comment by WillKoehrsen** [comment]
Yes, updating the docs would be very helpful! I don't think we need to update the `make` rule. It would be better if the EIA class itself outputted an error message when missing the API key. I'm not sure why this isn't happening since the code seems like it should: https://github.com/kmax12/gridstatus/blob/8d5898ad19ad20ebacd294901d39d239a949d8aa/gridstatus/eia.py#L34-L38

**Comment by tylercecil** [comment]
Coming back after vacation — I think #348 closes this out, thanks!
