### ISSUE TITLE
Handling rate limits in hit_ercot_api.

### ISSUE THREAD

**Issue by buckfeng** [kmax12/gridstatus#415]
while downloading 30 days of data using the `hit_ercot_api()` method, I got rate-limited with the following exception:

`requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.ercot.com/api/public-reports/np4-183-cd/dam_hourly_lmp?size=100000&deliveryDateFrom=2024-06-20&deliveryDateTo=2024-06-20&page=1`

To reproduce, call this following code in a loop, one day at a time for 30 days.  It would raise the error about 7 days in.

```python
import gridstatus.ercot_api.ercot_api as ercot_api

def dam_hourly_lmp_to_df(begin: datetime, end: datetime) -> pd.DataFrame:
    """
    Get the DAM hourly LMP data from the ERCOT API and return it as a DataFrame.

    Parameters:
    begin (datetime): The begin date of the date range for the data.
    end (datetime): Inclusive, the end date of the date range for the data.
    """

    ercotApi = ercot_api.ErcotAPI()
    dam_hourly_lmp_endpoint = "/np4-183-cd/dam_hourly_lmp"
    api_params = {
        "deliveryDateFrom": begin.strftime("%Y-%m-%d"),
        "deliveryDateTo": end.strftime("%Y-%m-%d"),
    }
    return ercotApi.hit_ercot_api(
        endpoint=dam_hourly_lmp_endpoint, verbose=True, **api_params
    )
```

The error actually happened on this line because `make_api_call()` didn't handle status 429 properly.
```python
        # The data comes back as a list of lists. We get the columns to
        # create a dataframe after we have all the data
        columns = [f["name"] for f in response["fields"]]
```

I added the following retries logic to the make_api_call() and was able to download 30 days of data.
```python
    def make_api_call(
        self,
        url,
        method="GET",
        api_params=None,
        data=None,
        parse_json=True,
        verbose=False,
    ):
        log(f"Requesting url: {url} with params: {api_params}", verbose)
        retries = 0
        delay = 3.0
        if method == "GET":
            while retries < 3:
                response = requests.get(url, params=api_params, headers=self.headers())
                retries += 1
                if response.ok:
                    break
                if response.status_code == 429 and retries < 3:
                    print(f"Rate limited, waiting {delay} seconds on retry {retries}")
                    time.sleep(delay)
                    delay = delay * 2
                else:
                    response.raise_for_status()
 ```

ErcotAPI class seemed to have implemented retries with gradually increasing delays.  But the retry function needs to be inside the `make_api_call()`.  It would be nice if retry can be done without tying up a thread by time.sleep.

**Comment by WillKoehrsen** [comment]
Thanks for the report! You're right that the current retries logic is inadequate. Do you want to open a PR to address the issue?

**Comment by buckfeng** [comment]
I'd give it a try.  can you assign the issue to me?  full disclosure - I am new to python.  you'd need to review my changes thoroughly.

**Comment by WillKoehrsen** [comment]
@buckfeng Can we close this now that #417 has been merged? Thank you for your contribution!
