### ISSUE TITLE
CAISO historical load giving parser error

### ISSUE THREAD

**Issue by m4rz910** [kmax12/gridstatus#68]
Hey, seeing a parser error when trying to pull some caiso load data...

```python

gridstatus.CAISO().get_historical_load(start=pd.Timestamp("1/1/2018").normalize(), end=pd.Timestamp("1/1/2019").normalize())
```

ParserError: Error tokenizing data. C error: Expected 1 fields in line 21, saw 2

**Comment by m4rz910** [comment]
I am trying to push a branch called tests with the following test but dont have those privileges. Can you enable them please?

```python
import pytest
import pandas as pd
import gridstatus

@pytest.mark.parametrize(
    "start, end",
    [
    (
        pd.Timestamp("01/01/2018").normalize(),
        pd.Timestamp("01/01/2019").normalize()
    ),
    
    (
        "01/01/2018",
        "01/01/2019"
    )
])
def test_historical_load(start,end):
    caiso = gridstatus.CAISO()
    caiso.get_historical_load(start=start,
                              end=end
                              )
 ```

**Comment by kmax12** [comment]
just gave you access. 

in this, case the data isn't available.

I'm using urls like this https://www.caiso.com/outlook/SP/History/20180101/demand.csv to get data and you can see that data is return a 404 page.

The earliest data that is available appears to be April 10, 2018 https://www.caiso.com/outlook/SP/History/20180410/demand.csv.
