### ISSUE TITLE
Load Bus LBMP Availability?

### ISSUE THREAD

**Issue by m4rz910** [kmax12/gridstatus#72]
Last week @kbaranko and I were chatting about the meaning of [NYISO "Generator" LMBPs](https://www.nyiso.com/energy-market-operational-data) and thought I would summarize some things I learned from poking around in some NYISO documentation. Hoping that this might help get more granular LBMP data available in the tool at some point (I have no urgent need for it personally at the moment).

* Definition of LBMP (location based marginal price) - the cost to provide the next MW of load at a specific location in the grid.
* A gen bus LBMP is calculated where generator injects power (easily available)
* A zonal LBMP is the load weighted-average of all the load bus LBMPs in that load zone (easily available)
   * Unfortunately it doesn't seem like NYISO publishes the load bus LBMPs on either of the two main NYISO websites
   * I dont think its possible to back-calculate each load bus LBMP, even if you have the sub-zonal load accessible through the [NYISO's Metering API](https://www.nyiso.com/documents/20142/27889215/NYISO%20Metering%20API%20User%20Guide.pdf/d8ed36d3-1a40-9584-6961-3fdb845ca4fa). @kmax12 as a sidenote, its unclear to me how extensive NYISOs APIs are since Iv only ever explored the [MIS website](http://mis.nyiso.com/public/) both gridstatus and NYISOToolkit are 'scraping' from.
   * FYI some load names  with their zones can be found at the bottom of the [MIS website](http://mis.nyiso.com/public/) 
   
 Some useful LBMP docs I came across...
  * https://www.nyiso.com/documents/20142/31589128/4%20MST%2017.1%20-%20MATC%20Incremental%20Redline%20v3.pdf/5f89445d-fd44-3b88-aaed-0031cb0eb744
  * https://www.nyiso.com/documents/20142/3037451/3-LMBP.pdf/f7682e03-e921-eaab-09bf-690524b5ade6

**Comment by kbaranko** [comment]
@m4rz910 thank you for the summary. Do you know what level of granularity NYISO offers load data through the Metering API and do you have any thoughts on what inputs are needed to estimate the ballpark LBMP at a load bus?

**Comment by kmax12** [comment]
Appreciate the notes. 

Do you know if the metering API is available yet? Looking at this slide, it appears it might not be ([source](https://www.nyiso.com/documents/20142/27889215/Meter%20Data%20Reporting%20Enhancement-API_BACWG_01-21-2022_Final.pdf/e5d52435-11bd-ac83-2b28-f8c659b0fbe8))

<img width="988" alt="image" src="https://user-images.githubusercontent.com/371792/199263259-5ed641af-a4d1-4e40-ab56-28f09ee8de38.png">

**Comment by m4rz910** [comment]
@kbaranko it looks like things work differently in New York with regard to load LMBPs. Generators are paid the generator LMBP and load pays the zonal LBMP according to [p30 of the Market Participant Manual](https://www.nyiso.com/documents/20142/3625950/mpug.pdf/c6ca83ca-ee6b-e507-4580-0bf76cd1da1b).

**Comment by m4rz910** [comment]
@kmax12 I have not used their metering API yet either
