### ISSUE TITLE
Add natural gas price data

### ISSUE THREAD

**Issue by m4rz910** [kmax12/gridstatus#78]

**Comment by kmax12** [comment]
We have gas prices for CAISO [here](https://docs.gridstatus.io/en/latest/autoapi/gridstatus/index.html#gridstatus.CAISO.get_gas_prices)


What do you think is a good source for this for everywhere else? Does EIA have something?

**Comment by m4rz910** [comment]
No free centralized source that I know. Andrew Gelston linked me [this site](https://naesb.org//members/urls_of_pipelines.htm) that lists the raw pages for all the major pipeline systems. Parsing each one of these sites and maintaining it might be pretty big effort to make and maintain...

**Comment by WillKoehrsen** [comment]
Duplicated by #264. We can move the discussion there.
